Question_repo/apps/accounts/urls.py
from django.conf.urls import url
from . import views

#TemplateView  ==>  基于类的视图

urlpatterns = [
    # url(r'register/$', TemplateView.as_view(template_name="accounts/register.html")),
    # url(r'register/$', views.register, name="register"),
    url(r'^register/$', views.Register.as_view(), name='register'),
    # url(r'^login/$',TemplateView.as_view(template_name='accounts/login.html'),name='login'),
    #基于类的url
    url(r'^login/$',views.Login.as_view(),name='login'),
    #基于函数的url
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^password/forget/$',views.PasswordForget.as_view(), name='password_forget'),
    url(r'password/reset/(\w+)$', views.PasswordReset.as_view(), name="password_reset"),
]

Question_repo/apps/apis/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    #   获取手机验证码
    url(r'^get_mobile_captcha/$', views.get_mobile_captcha, name='get_mobile_captcha'),
    #   获取图形验证码
    url(r'^get_captcha/$', views.get_captcha, name='get_captcha'),
    #   检查图形验证码
    url(r'^check_capcha/$', views.check_captcha, name='check_captcha'),
    #datable所有问题
    url(r'^questions/$', views.questions, name='questions'),
    # 参考答案的接口
    url(r'^answer/(?P<id>\d+)/$', views.AnswerView.as_view(), name='answer'),
    # 某题所有人作答情况接口
    url(r'^other_answer/(?P<id>\d+)/$', views.OtherAnswerView.as_view(),name='other_answer'),
    # 答案收藏接口
    url(r'^answer/collection/(?P<id>\d+)/$', views.AnswerCollectionView.as_view(), name='answer_collection'),
    # 问题收藏接口
    url(r'^question/collection/(?P<id>\d+)/$',views.QuestionCollectionView.as_view(), name='question_collection'),
    url(r'^change_avator/$', views.ChangeAvator.as_view(), name='change_avator'),
    url(r'^question/contribute/$', views.QuestionsContributeView.as_view(), name='question_contribute'),
]

Question_repo/apps/repo/urls.py
from django.conf.urls import url
from . import views

#TemplateView  ==>  基于类的视图

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'question/$',views.questions ,name='questions'),
    #  捕获一个参数  详情页url地址  基于类的视图
    #  参数命名题目id
    url(r'^question_detail/(?P<id>\d+)/$', views.QuestionDetail.as_view(), name='question_detail'),
]

Question_repo/apps/usercenter/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView
from . import views

#TemplateView  ==>  基于类的视图

urlpatterns = [
    url(r'^profile/$',views.ProfileView.as_view(),name='profile'),
    url(r'^change_passwd/$', views.ChangePasswordView.as_view(), name='change_passwd'),
    url(r'^answer/$',views.AnswerView.as_view(),name='answer'),
    url(r'^collect/$',views.CollectView.as_view(),name='collect'),
    url(r'^contribute/$',views.ContributeView.as_view(), name='contribute'),
    url(r'^approval/$', views.ApprovalView.as_view(), name='approval'),
    url(r'^approval/(?P<id>\d+)/$', views.ApprovalPassView.as_view(), name='approval_pass'),
]

Question_repo/question_repo/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from apps.repo import views
from django.views.static import serve
from .settings import MEDIA_ROOT
from django.views.generic import TemplateView
from django.conf.urls import handler403,handler404,handler500
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^index/$',views.index,name='index'),
    url(r'^accounts/',include('apps.accounts.urls', namespace='accounts')),
    url(r'^apis/',include('apps.apis.urls', namespace='apis')),
    url(r'^repo/',include('apps.repo.urls', namespace='repo')),
    url(r'^usercenter/',include('apps.usercenter.urls',namespace='usercenter')),
    # meida 处理
    url(r'^media/(?P<path>.*)$', serve, {"document_root":MEDIA_ROOT}),
    # ckeditor
    url(r'^cheditor/', include('ckeditor_uploader.urls')),
]

# handler403 = views.custom_403
# handler404 = views.custom_404
# handler500 = views.custom_500

Question_repo/apps/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from easy_thumbnails.fields import ThumbnailerImageField
from django.db.models.fields.files import ImageFieldFile
import os
from question_repo.settings import MEDIA_ROOT,THUMB_SIZE
from libs.make_thumb import make_thumb

# Create your models here.

#继承自AbstractUser
class User(AbstractUser):
    realname = models.CharField(max_length=8, verbose_name="真实姓名")
    mobile = models.CharField(max_length=11, verbose_name="手机号")
    qq = models.CharField(max_length=11, verbose_name="QQ号")
    # avator_sor = ThumbnailerImageField(upload_to="avator/%Y%m%d/", default="avator/default.jpg", verbose_name="头像")
    avator_sor = ThumbnailerImageField(upload_to="avator/%Y%m%d/", default="avator/girls_02.jpg", verbose_name="头像")
    avator_sm = models.ImageField("头像缩略图", upload_to="avator/%Y%m%d/", default='avator/girls_02.jpg.50x50_q85_crop.jpg')

    def save(self, *args, **kwargs):
        # print('abcdefgxxxs')
        super().save()

        if self.avator_sor.name == 'avator/girls_02.jpg':
            return

        # /Users/apple/PycharmProjects/T_question_repo/media
        if not os.path.exists(os.path.join(MEDIA_ROOT,self.avator_sor.name)):
            return

        '''
        >>> base,ext = os.path.splitext(user.avator_sor.name)
        >>> base,ext
        ('avator/girls_02', '.jpg')
        '''

        base, ext = os.path.splitext(self.avator_sor.name)
        thumb_pixbuf = make_thumb(os.path.join(MEDIA_ROOT, self.avator_sor.name),size=THUMB_SIZE)
        if thumb_pixbuf:
            # 缩略图文件的保存路径
            thumb_path = os.path.join(MEDIA_ROOT, base+f".{THUMB_SIZE}x{THUMB_SIZE}"+ext)
            # 缩略图相对路径
            relate_thumb_path = base+f'.{THUMB_SIZE}x{THUMB_SIZE}'+ext
            # avator/20190513/bg_02.70x70.jpg
            print(relate_thumb_path)

            thumb_pixbuf.save(thumb_path)
            #保存字段的值
            self.avator_sm = ImageFieldFile(self, self.avator_sm,relate_thumb_path)
            super().save()


class FindPassword(models.Model):
    verify_code = models.CharField(max_length=128, verbose_name="验证码")
    email = models.EmailField(verbose_name="邮箱",unique=True)
    creat_time = models.DateTimeField(auto_now=True, verbose_name="重置时间")
    status = models.BooleanField(default=False, verbose_name="是否已重置")

Question_repo/apps/accounts/forms.py
from django import forms
from django.forms import widgets
from django.core.exceptions import ValidationError
from .models import User
from django.contrib.auth.hashers import check_password as auth_check_password

"""

注册表单：
        表单：用户名，手机号，两个密码，验证码
        - 添加用户名检查：用户名不能重复
        - 添加手机号检查： 手机号不能重复
        - 添加密码检查： 两次密码要相同
        - 添加密码复杂度检查： 不能为纯数字
"""


# Create your models here.

#继承自AbstractUser
# 用户注册
class RegisterForm(forms.Form):
    username = forms.CharField(label="用户名", max_length="24", widget=widgets.TextInput(attrs={"class":"form-control", "placeholder": "请输入用户名"}))
    mobile = forms.CharField(label="手机号", max_length="24",widget=widgets.TextInput(attrs={"class":"form-control", "placeholder": "请输入手机号"}))
    password = forms.CharField(label="密 码", widget=widgets.PasswordInput(attrs={"class":"form-control", "placeholder": "请输入密码"}))
    password2 = forms.CharField(label="密 码2", widget=widgets.PasswordInput(attrs={"class":"form-control", "placeholder": "请再输入密码"}))
    mobile_captcha = forms.CharField(label="验证码", widget=widgets.TextInput(attrs={"style":"width: 160px;padding: 10px", "placeholder":"验证码", "error_messages": {"invalid": "验证码错误"}}))


    "cleaned_data 就是读取表单返回的值，返回类型为字典dict型email=cleaned_data['email']  读取name为 ‘email’的表单提交值，并赋予 email变量"
    def clean_username(self):
        ret = User.objects.filter(username=self.cleaned_data.get("username"))
        if not ret:
            return self.cleaned_data.get("username")
        else:
            raise ValidationError("用户名已注册")

    def clean_mobile(self):
        ret = User.objects.filter(mobile=self.cleaned_data.get("mobile"))
        if not ret:
            return self.cleaned_data.get("mobile")
        else:
            raise ValidationError("手机号已绑定")

    def clean_password(self):
        data = self.cleaned_data.get("password")
        if not data.isdigit():
            return self.cleaned_data.get("password")
        else:
            raise ValidationError("密码不能全是数字")

    def clean(self):
        if self.cleaned_data.get("password") == self.cleaned_data.get("password2"):
            print(self.cleaned_data)
            return self.cleaned_data
        else:
            raise ValidationError("两次密码不一致")


class LoginForm(forms.ModelForm):
    captcha = forms.CharField(label="验证码", widget=widgets.TextInput(attrs=
                {"style":"width: 160px;padding: 10px", "placeholder":"验证码", "onblur":"check_captcha()", "error_messages": {"invalid": "验证码错误"}}))

    class Meta:
        model = User
        fields = ['username','password']
        widgets = {'username': widgets.TextInput(attrs={"class": "form-control", "placeholder":"用户名"}),"password": widgets.PasswordInput(attrs={"class": "form-control","placeholder": "密 码"})}

    def check_password(self):
        print('check password')
        username = self.cleaned_data['username']
        password = self.cleaned_data['password']
        try:
            user = User.objects.get(username=username)
            return user, auth_check_password(password, user.password)
        except:
            return None, False

Question_repo/apps/accounts/views.py
from django.contrib import auth
from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.views.generic.base import View
from .forms import RegisterForm,LoginForm
from .models import User
import logging
from django.core.cache import cache
logger = logging.getLogger('account')


def index(request):
    return render(request, 'accounts/index.html')


class Register(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, 'accounts/register.html',{"form":form})

    #Ajax提交表单
    def post(self,request):
        # request.POST ==> 获取前端页面上一post方式提交的表单中的信息
        form = RegisterForm(request.POST)
        ret = {}
        if form.is_valid():
            username = form.cleaned_data["username"]
            password= form.cleaned_data["password"]
            mobile = form.cleaned_data["mobile"]
            mobile_capcha = form.cleaned_data["mobile_captcha"]
            mobile_capcha_redis = cache.get(mobile)
            if mobile_capcha == mobile_capcha_redis:
                user = User.objects.create(username=username, password=make_password(password))
                user.save()
                ret['status'] = 200
                ret['msg'] = '注册成功'
                #############################
                return redirect(reverse("accounts:login"))
    ##########################################################
            else:
                ret["status"] = 300
                ret["msg"] = "验证码输入有误"
        else:
            ret["status"] = 400
            ret["msg"] = "填入的用户名或者密码不符合标准"
        return render(request,"accounts/register.html",{"form":form,"msg":ret})

class Login(View):
    def get(self, request):
        # 如果用户已经登录 ==> 跳转到index页面即可
        if request.user.is_authenticated:
            return redirect(reverse('repo:index'))
        form = LoginForm()
        request.session["next"] = request.GET.get('next',reverse('repo:index'))
        return render(request, "accounts/login.html", {"form":form})

    def post(self, request):
        # 表单数据绑定
        form = LoginForm(request.POST)
        username = request.POST.get("username")
        password = request.POST.get("password")
        captcha = request.POST.get("captcha")
        session_captcha_code = request.session.get("captcha_code","")
        logger.debug(f"登录提交验证码:{captcha}-{session_captcha_code}")
        # if captcha.lower() == session_captcha_code.lower():
        user = auth.authenticate(username=username, password=password)
        if user is not None and user.is_active:
            auth.login(request, user)
            logger.info(f"{username}登录成功")
            msg = '登录成功'
            # 跳转到next
            return redirect(request.session.get("next",'/'))
        msg = "用户名或密码错误"
            # logger.error(f"{username}登录失败, 用户名或密码错误")
        # else:
        #     msg = "验证码错误"
        #     logger.error(f"{username}登录失败, 验证码错误")
        return render(request, "accounts/login.html", {"form": form, "msg":msg})


def logout(request):
    username = request.POST.get('username')
    logger.info('{}登录成功'.format(username))
    auth.logout(request)
    return redirect(reverse('accounts:login'))




from .models import FindPassword
import random,string
class PasswordForget(View):
    def get(self, request):
        return render(request, 'accounts/uc_findpassword.html')

    def post(self, request):
        print('xxxxxxxxxxxx')
        email = request.POST.get('email')
        if email and User.objects.filter(email=email):
            verify_code = "".join(random.choices(string.ascii_lowercase+string.digits,k=128))
            url = '{0}://{1}/accounts/password/reset/{2}?email={3}'.format(request.scheme,request.META['HTTP_HOST'], verify_code, email)
            print(url)
            '''
            >>> FindPassword.objects.get_or_create(email=email)
            (<FindPassword: FindPassword object>, False)
            '''
            ret = FindPassword.objects.get_or_create(email=email)
            print(ret[0].verify_code)
            # 第一次发送邮件时ret[0].verify_code 是没有值的
            ret[0].verify_code = verify_code
            ret[0].status = False
            ret[0].save()
            # print('发邮件')
            send_mail("注册用户验证",url, None, [email])
            return HttpResponse("邮件发送成功")
        else:
            msg = "输入的邮箱不存在"
            return render(request, "accounts/uc_findpassword.html",{"msg":msg})




class PasswordReset(View):
    # url上面的数据 verify_code
    def get(self, request, verify_code):
        import datetime
        # 零时区减去三十分钟 ==> 三十分钟之前零时区的时间 ==> 数据库添加数据默认是以零时区为标准计时的
        create_time_newer = datetime.datetime.utcnow() - datetime.timedelta(minutes=30)
        print(create_time_newer, verify_code)
        email = request.GET.get("email")
        # find_password = FindPassword.objects.filter(status=False, verify_code=verify_code, creat_time__gte=create_time_newer, email=email)
        # 邮箱、verify_code、status=False、时间近30分钟
        # status ==> 是否被重置 False ==> 没有被重置
        # gte ==> 大于等于
        find_password = FindPassword.objects.filter(status=False, verify_code=verify_code, email=email,creat_time__gte=create_time_newer)
        if verify_code and find_password:
            # 这里是要先验证链接是否有效，有效的话就跳转到重置密码页面 ==> 之后用户输入密码之后 ==> 传递到后端 ==> 用此时图函数的post方法来判断数据
            return render(request, "accounts/uc_resetpassword.html")
        else:
            return HttpResponse("链接失效或有误")

    def post(self, request, verify_code):
        pass

Question_repo/templates/accounts/403_custom.html
这个是儿童编号为{{ data }} 的小孩

Question_repo/templates/accounts/base.html
{% load staticfiles %}
{% load thumbnail %}
{#{% load thumbnail %}#}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content={{ descrip.one }}{{ descrip.two }}{{ descrip.three }}{{ descrip.four }}>
    <link rel="shortcut icon" href="img/favicon.html">

    <title>{% block title %}{% endblock %}{{ site.WEB_NAME }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
{#    <link href="{% static 'css/bootstrap-reset.css' %}" rel="stylesheet">#}
    <!--external css-->
    <link href="{% static 'assets/font-awesome/css/font-awesome.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/style-responsive.css' %}" rel="stylesheet" />
    {% block load_css %}
    {% endblock %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 tooltipss and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'js/html5shiv.js' %}"></script>
      <script src="{% static 'js/respond.min.js' %}"></script>
    <![endif]-->
  <style>
      body{
          font-size: 14px; !important;
      }
  </style>
  </head>

  <body>
<div class="container">

  <section id="container" class="">
      <!--header start-->
      <header class="header white-bg">
          <!--logo start-->
          <a href="#" class="logo" >三创<span>题库</span></a>
          <!--logo end-->
          <div class="top-nav">
              <!-- Collect the nav links, forms, and other content for toggling -->
              <ul class="nav navbar-nav">
                <li class="active">
                      <a class="" href="{% url 'repo:index' %}">
{#                          <i class="icon-dashboard"></i>#}
                          <span> 首页 </span>
                      </a>
                </li>
                <li class="">
                  <a class="" href="{% url 'repo:questions' %}">
{#                      <i class="icon-dashboard"></i>#}
                      <span> 校招题 </span>
                  </a>
                </li>
{#                <li class="">#}
{#                  <a class="" href="{% url 'repo:questions' %}">#}
{#                      <i class="icon-dashboard"></i>#}
{#                      <span> 试卷题 </span>#}
{#                  </a>#}
{#                </li>#}
{#                <li class="">#}
{#                  <a class="" href="{% url 'repo:questions' %}">#}
{#                      <i class="icon-dashboard"></i>#}
{#                      <span> 知识库 </span>#}
{#                  </a>#}
{#                </li>#}
{#                <li class="">#}
{#                  <a class="" href="{% url 'in_approval' %}">#}
{#                      <i class="icon-dashboard"></i>#}
{#                      <span> 待审题目 </span>#}
{#                      <span class="label label-danger pull-right mail-info">2</span>#}
{#                  </a>#}
{#                </li>#}
              </ul>
              <ul class="nav pull-right top-menu">
                  <li>
                      <form action="{% url 'repo:questions' %}">
                         <input type="text" class="form-control search" placeholder="Search" name="search" id="search" value="{{ search_key }}">
                      </form>
                  </li>
                  <!-- user login dropdown start-->
{#                    如果用户已经登录#}
                  {% if user.is_authenticated %}
                  <li class="dropdown">
                      <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                          <img alt="" src="{{ user.avator_sor | thumbnail_url:'avatar' }}" height="30px">
{#                          <img alt="" src="{% static 'img/avatar1_small.jpg' %}">#}
                          <span class="username">{{ user }}</span>
                          <b class="caret"></b>
                      </a>
                      <ul class="dropdown-menu">
                          <div class="log-arrow-up"></div>
                          <li><a class="" href="{% url 'usercenter:profile' %}"> 个人资料 </a></li>
                          <li><a class="" href="{% url 'usercenter:change_passwd' %}"> 修改密码 </a></li>
                          <li><a class="" href="{% url 'usercenter:answer' %}"> 我的回答 </a></li>
                          <li><a class="" href="{% url 'usercenter:collect' %}"> 我的收藏 </a></li>
                          <li><a class="" href="#myModal-1" data-toggle="modal"> 贡献题目 </a></li>
                          <li><a class="" href="{% url 'usercenter:contribute' %}"> 我的贡献 </a></li>
                          <li><a class="" href="#"> 退出 </a></li>
                      </ul>
                  </li>
                  {% else %}
                  <div style="float:right; margin-top:15px;margin-left:10px;">
                  ############################################################################################
                        <a href="{% url 'accounts:login' %}">登录</a>|<a href="{% url 'accounts:register' %}">注册</a>
                  ############################################################################################
                  </div>
                  {% endif %}
                  <!-- user login dropdown end -->
              </ul>
          </div>
      </header>
      <!--header end-->

      <!--main content start-->
      <section id="main-content">
          <section class="wrapper">
              <!-- page start-->
              {% block content %}
              Page content goes here
              {% endblock %}
              <!-- page end-->
          </section>
      </section>
      <!--main content end-->
  </section>
</div>

{% include 'accounts/crontribute_modal.html' %}

    <!-- js placed at the end of the document so the pages load faster -->
    <script src="{% static 'js/jquery.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
    <script src="{% static 'js/jquery.nicescroll.js' %}" type="text/javascript"></script>

    <!--common script for all pages-->
    <script src="{% static 'js/common-scripts.js' %}"></script>

    {% block load_js %}
    {% endblock %}
  </body>
</html>

Question_repo/templates/accounts/register.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="Mosaddek">
    <meta name="keyword" content="FlatLab, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina">
    <link rel="shortcut icon" href="">
    <title>Register</title>

    <!-- Bootstrap core CSS -->
    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/bootstrap-reset.css" rel="stylesheet">
    <!--external css-->
    <link href="/static/assets/font-awesome/css/font-awesome.css" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="/static/css/style.css" rel="stylesheet">
    <link href="/static/css/style-responsive.css" rel="stylesheet">
    <script src="jquery-3.4.1.min.js"></script>
    <!-- 提示工具 -->
    <link rel="stylesheet" type="text/css" href="{% static 'assets/gritter/css/jquery.gritter.css' %}" />
    <script src="{% static 'js/jquery.js' %}"></script>
    <script type="text/javascript" src="{% static 'assets/gritter/js/jquery.gritter.js' %}"></script>
</head>
  <body class="login-body" style="">
    <div class="container">
      <form class="form-signin" id="register_form" method="post">
         {% csrf_token %}
        <h2 class="form-signin-heading">用户注册</h2>
        <div class="login-wrap">
            {{ form.username }}
            {{ form.password }}
            {{ form.password2 }}
            {{ form.mobile }}
            {{ form.mobile_captcha }}
            <input onclick="sendmessage(this,60);" type="button" value="发送短信" class="btn btn-info" style="height:38px;width: 125px;"><p></p>
            <button class="btn btn-lg btn-login btn-block" type="submit" id="register_btn">注册</button>
            <label class="checkbox">
                <span class="pull-right"> 已有帐号， <a href="http://127.0.0.1:8000/accounts/login/"> 请登录 </a></span>
            </label>
        </div>
      </form>
{#        {{ msg }}#}
    </div>
  <script>
    function sendmessage(obj,second){
        var telRegex = /(13|14|15|17|18)\d{9}/;
        if(telRegex.test($.trim($("#id_mobile").val()))){
		    $.ajax({
                url: "{% url 'apis:get_mobile_captcha' %}",
                type: "GET",
                dataType: "json",
                data: {"mobile": $("#id_mobile").val()},
                success: function (data) {
                    $.gritter.add({
                        // (string | mandatory) the heading of the notification
                        title: '提交结果',
                        // (string | mandatory) the text inside the notification
                        //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                        text: data.msg
                    });
                }
            });
			countDown(obj,second)
        } else{
            $.gritter.add({
                // (string | mandatory) the heading of the notification
                title: '提交结果',
                // (string | mandatory) the text inside the notification
                //text: 'This will fade out after a certain amount of time. Vivamus eget tincidunt velit. Cum sociis natoque penatibus et <a href="#" style="color:#ccc">magnis dis parturient</a> montes, nascetur ridiculus mus.'
                text: '手机号有误'
            });
        }
    }

	function countDown(obj,second){
    // 如果秒数还是大于0，则表示倒计时还没结束
     if(second>=0){
          // 获取默认按钮上的文字
          if(typeof buttonDefaultValue === 'undefined' ){
            buttonDefaultValue =  obj.defaultValue;
        }
        // 按钮置为不可点击状态
        obj.disabled = true;
        // 按钮里的内容呈现倒计时状态
        obj.value = buttonDefaultValue+'('+second+')';
        // 时间减一
        second--;
        // 一秒后重复执行
        setTimeout(function(){countDown(obj,second);},1000);
        // 否则，按钮重置为初始状态
        }else{
        // 按钮置未可点击状态
        obj.disabled = false;
        // 按钮里的内容恢复初始状态
        obj.value = buttonDefaultValue;
       }
    }
  </script>
</body>
</html>

Question_repo/templates/accounts/uc_left.html
<div class="panel">
  <div class="panel-body">
    <ul class="nav nav-pills nav-stacked">
{#    url 'usercenter:profile' ==> 在前端这个表示一个语句 ==> 有点类似于后端的反向解析reverse('usercenter:profile')语句 #}
    {% url 'usercenter:profile' as usercenter_profile %}
    {% url 'usercenter:change_passwd' as usercenter_change_passwd %}
    {% url 'usercenter:answer' as usercenter_answer %}
    {% url 'usercenter:collect' as usercenter_collect %}
    {% url 'usercenter:contribute' as usercenter_contribute %}
    {% url 'usercenter:approval' as usercenter_approval %}

{#    x{{ request.path }}x#}
{#    x{{ request.url ==> 没有值 }}x#}
{#    /usercenter/approval/#}
{#    x{{ usercenter_profile }}x#}
{#    x/usercenter/profile/x#}

    <li role="presentation" class="{% if request.path ==  usercenter_profile %}active{% endif %}"><a href="{{ usercenter_profile }}">个人资料</a></li>
    <li role="presentation" class="{% if request.path == usercenter_change_passwd %}active{% endif %}"><a href="{{ usercenter_change_passwd }}">修改密码</a></li>
    <li role="presentation" class="{% if request.path == usercenter_answer %}active{% endif %}"><a href="{{ usercenter_answer }}">我的回答</a></li>
    <li role="presentation" class="{% if request.path == usercenter_collect %}active{% endif %}"><a href="{{ usercenter_collect }}">我的收藏</a></li>
    <li role="presentation" class="{% if request.path == usercenter_contribute %}active{% endif %}"><a href="{{ usercenter_contribute }}">我的贡献</a></li>
    <li role="presentation" class="{% if request.path == usercenter_approval %}active{% endif %}"><a href="{{ usercenter_approval }}">待审题目</a></li>
    </ul>
  </div>
</div>

Question_repo/templates/accounts/uc_resetpassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>忘记密码</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    密码1:<input type="password" placeholder="请输入密码" name="password1">
    密码2:<input type="password" placeholder="请再次输入密码" name="password2">
    <input type="submit" value="提交">
    {{ msg }}
</form>
</body>
</html>